services:
  - type: web
    name: connect-meet-frontend
    env: static
    buildCommand: npm --prefix frontend install && npm --prefix frontend run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: conect-meet-backend
    env: node
    buildCommand: npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
